# Crear una variable
# Crear una regla para que ejecute un hello world
# Crear un directorio y un archivo
# Establecer el contenido de un archivo (sobreescribir)
# Añadir contenido a un archivo (sin sobreescribir)
# Mostrar el contenido de un archivo
# Limpiar los archivos y directorios creados
# Ejecutar clean y luego create
# Declarar PHONY